zoom_conference_key: RpwQ83ZTSOi2UKYxzuA5qg
zoom_conference_secret: 0wJBubH2DUMOJsXL0lSFCgj8IXrj1vOT8WjS
zoom_conference_url: api.zoom.us/v2/
zoom_conference_webhooks_enabled: 0
zoom_conference_webhooks_username: ''
zoom_conference_webhooks_password: ''
zoom_conference_debug: 1
